package food;

public enum Ingredients {
    Apples,
    Bananas,
    Citrus_fruits,
    Grapes,
    Mango,
    Papaya,
    Passion_fruit,
    Pomegranate,
    Peaches,
    Asparagus,
    Beets,
    Bell_peppers,
    Broccoli,
    Mushrooms,
    Butternut,
    Carrots,
    Collard_greens,
    Courgettes,
    Hot_peppers,
    Mustard_greens,
    Spinach,
    Tomatoes,
    Leeks,
    Winter_squashes,
    Dandelion_greens,
    Kale,
    Okra,
    Sweet_potatoes,
    Parsley,
    Pumpkins
}
